spring:
  application:
    name: team-service

  profiles:
    default: local

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

team:
  name: ${TEAM_NAME:}

aws:
  region: ${AWS_REGION:ap-northeast-2}
  s3:
    bucket: ${S3_BUCKET_NAME:}

management:
  endpoints:
    web:
      exposure:
        include: health, info

  endpoint:
    health:
      show-details: never
      show-components: never
      probes:
        enabled: false