spring:
  application:
    name: team-service

  profiles:
    default: local

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: never
      show-components: never
      probes:
        enabled: false